server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:account-service-data.sql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  health:
    eureka:
      enabled: false