spring:
  datasource:
    url: jdbc:postgresql://fraud-db:5432/MonitoringService
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/