spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/