spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/